export enum FieldValues {
  address_components = "address_components",
  adr_address = "adr_address",
  business_status = "business_status",
  formatted_address = "formatted_address",
  geometry = "geometry",
  icon = "icon",
  icon_mask_base_uri = "icon_mask_base_uri",
  icon_background_color = "icon_background_color",
  name = "name",
  permanently_closed = "permanently_closed",
  photos = "photos",
  place_id = "place_id",
  plus_code = "plus_code",
  type = "type",
  url = "url",
  utc_offset_minutes = "utc_offset_minutes",
  vicinity = "vicinity",
}
